version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: university_postgres
    restart: always
    environment:
      POSTGRES_DB: university_db
      POSTGRES_USER: university_user
      POSTGRES_PASSWORD: university_pass
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
